created readme
Vitalbka/taxi-service pull request #1
Opened 2021-12-14 18:46 UTC by Vitalbka

2021-12-15 06:43 UTC, SergiiSV commented on .gitignore
> +*logs
does "logs" should be like "logs/*" like your folders?

2021-12-15 06:44 UTC, SergiiSV commented on src/main/resources/log4j2.xml 
> +</Configuration>
add empty line

2021-12-15 06:45 UTC, SergiiSV requested changes
2 coments

2021-12-15 12:10 UTC, SergiiSV approved these changes

2021-12-15 12:58 UTC, Nick97-git requested changes
- DeleteCarController, DeleteDriverController, DeleteManufacturerController -> remove /all from /cars/all, /drivers/all, /manufacturers/all url patterns

2021-12-15 12:58 UTC, Nick97-git commented on README.md
>  # taxi-service
```suggestion
# Taxi-service
```

2021-12-15 12:58 UTC, Nick97-git commented on README.md
> +- track your cars as a driver
rewrite this part, it's very similar to one of the examples

2021-12-15 12:58 UTC, Nick97-git commented on README.md
> +[logo]: https://mate-academy-images.s3.eu-central-1.amazonaws.com/car_diagram_db_2_4f50942103.png
remove this image or create your own, it's very popular

2021-12-15 12:58 UTC, Nick97-git commented on src/main/webapp/WEB-INF/views/index.jsp
> +    <tr><td><a href="${pageContext.request.contextPath}/cars/by_driver">All my Cars</a></td></tr>
```suggestion
    <tr><td><a href="${pageContext.request.contextPath}/drivers/cars">All my Cars</a></td></tr>
```

2021-12-16 14:01 UTC, Nick97-git approved these changes

2022-01-04 15:34 UTC, merged